name       : matcha-gtk-theme
version    : '20200509'
release    : 7
source     :
    - https://github.com/vinceliuice/Matcha-gtk-theme/archive/2020-05-09.tar.gz : 6c9e4cecb639ad07127ae7561895a92a4796c873210af73baef6832f2a1f37d4
homepage   : https://github.com/vinceliuice/Matcha-gtk-theme
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Matcha is a flat Design theme for GTK 3, GTK 2 and Gnome-Shell
description: |
    Matcha is a flat Design theme for GTK 3, GTK 2 and Gnome-Shell based on Arc gtk theme.
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
install    : |
    install -dm00755 $installdir/usr/share/themes
    ./install.sh --dest $installdir/usr/share/themes
    rm -rf $installdir/usr/share/themes/*/{cinnamon,unity}
