name       : matcha-gtk-theme
version    : 2021.12.25
release    : 23
source     :
    - https://github.com/vinceliuice/Matcha-gtk-theme/archive/refs/tags/2021-12-25.tar.gz : 48c0ebd817ff55b0c40ff6753202c01777311955e8ef194ff22ba7757788e87d
homepage   : https://github.com/vinceliuice/Matcha-gtk-theme
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Matcha is a flat Design theme for GTK 4, GTK 3, GTK 2 and Gnome-Shell
description: |
    Matcha is a flat Design theme for GTK 4, GTK 3, GTK 2 and Gnome-Shell based on Arc gtk theme.
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
install    : |
    install -dm00644 $installdir/usr/share/themes
    ./install.sh --dest $installdir/usr/share/themes
    rm -rf $installdir/usr/share/themes/*/{cinnamon,unity}

    # Remove hdpi and xhdpi xfwm4 theme support
    rm -rf $installdir/usr/share/themes/*hdpi*
