name       : matcha-gtk-theme
version    : '20210409'
release    : 17
source     :
    - https://github.com/vinceliuice/Matcha-gtk-theme/archive/refs/tags/2021-04-09.tar.gz : a589459eeb0552665bffd0a5de851c0fa7a4b4dbae0ba995f93271b11ced64d2
homepage   : https://github.com/vinceliuice/Matcha-gtk-theme
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Matcha is a flat Design theme for GTK 4, GTK 3, GTK 2 and Gnome-Shell
description: |
    Matcha is a flat Design theme for GTK 4, GTK 3, GTK 2 and Gnome-Shell based on Arc gtk theme.
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
install    : |
    install -dm00644 $installdir/usr/share/themes
    ./install.sh --dest $installdir/usr/share/themes
    rm -rf $installdir/usr/share/themes/*/{cinnamon,unity}
