name       : matcha-gtk-theme
version    : 2019.05.09
release    : 1
source     :
    - https://github.com/vinceliuice/matcha/archive/2019_05_09.tar.gz : 66b992232f3c48bccd938c97ebc54b1ee5efb4a97cead182c9de266399e27fe1
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Matcha is a flat Design theme for GTK 3, GTK 2 and Gnome-Shell
description: |
    Matcha is a flat Design theme for GTK 3, GTK 2 and Gnome-Shell based on Arc gtk theme.
rundeps    : 
    - gtk2-engine-murrine
    - gtk-engines
install    : |
    install -dm00755 $installdir/usr/share/themes
    ./Install --dest $installdir/usr/share/themes
    rm -rf $installdir/usr/share/themes/*/{cinnamon,unity,xfwm4}
