name       : matcha-gtk-theme
version    : '20200206'
release    : 4
source     :
    - https://github.com/vinceliuice/matcha/archive/2020-02-06.tar.gz : 597b42c8110567b8e343dd290f1f13a169ffe8e151efe8dc7683bf173c3397b0
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Matcha is a flat Design theme for GTK 3, GTK 2 and Gnome-Shell
description: |
    Matcha is a flat Design theme for GTK 3, GTK 2 and Gnome-Shell based on Arc gtk theme.
rundeps    :
    - gtk2-engine-murrine
    - gtk-engines
install    : |
    install -dm00755 $installdir/usr/share/themes
    ./Install --dest $installdir/usr/share/themes
    rm -rf $installdir/usr/share/themes/*/{cinnamon,unity,xfwm4}
