name       : matcha-gtk-theme
version    : '20201023'
release    : 12
source     :
    - https://github.com/vinceliuice/Matcha-gtk-theme/archive/2020-10-23.tar.gz : 6c50513ea2f235e5693aaf3d7168451ab2d8ff3a0ca7352b17577ebf8d76f8f0
homepage   : https://github.com/vinceliuice/Matcha-gtk-theme
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Matcha is a flat Design theme for GTK 3, GTK 2 and Gnome-Shell
description: |
    Matcha is a flat Design theme for GTK 3, GTK 2 and Gnome-Shell based on Arc gtk theme.
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
install    : |
    install -dm00644 $installdir/usr/share/themes
    ./install.sh --dest $installdir/usr/share/themes
    rm -rf $installdir/usr/share/themes/*/{cinnamon,unity}
