name       : matcha-gtk-theme
version    : '20201005'
release    : 11
source     :
    - https://github.com/vinceliuice/Matcha-gtk-theme/archive/2020-10-05.tar.gz : 7ce69a25f9f5cf6b6e50519dfff9e9a8783f916383e5a3c3c68d493135d88d85
homepage   : https://github.com/vinceliuice/Matcha-gtk-theme
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Matcha is a flat Design theme for GTK 3, GTK 2 and Gnome-Shell
description: |
    Matcha is a flat Design theme for GTK 3, GTK 2 and Gnome-Shell based on Arc gtk theme.
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
install    : |
    install -dm00644 $installdir/usr/share/themes
    ./install.sh --dest $installdir/usr/share/themes
    rm -rf $installdir/usr/share/themes/*/{cinnamon,unity}
