name       : matcha-gtk-theme
version    : '20210602'
release    : 18
source     :
    - https://github.com/vinceliuice/Matcha-gtk-theme/archive/refs/tags/2021-06-02.tar.gz : 77181ab467a3583dec16329757be2dece64db0cc51cf6438005bc4b90c763250
homepage   : https://github.com/vinceliuice/Matcha-gtk-theme
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Matcha is a flat Design theme for GTK 4, GTK 3, GTK 2 and Gnome-Shell
description: |
    Matcha is a flat Design theme for GTK 4, GTK 3, GTK 2 and Gnome-Shell based on Arc gtk theme.
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
install    : |
    install -dm00644 $installdir/usr/share/themes
    ./install.sh --dest $installdir/usr/share/themes
    rm -rf $installdir/usr/share/themes/*/{cinnamon,unity}
