name       : matcha-gtk-theme
version    : 2019.09.07
release    : 2
source     :
    - https://github.com/vinceliuice/matcha/archive/v2019-07.tar.gz : b1de707a85a148cb29c210facb213500dae32247acc94a28e997010de7e3a641
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Matcha is a flat Design theme for GTK 3, GTK 2 and Gnome-Shell
description: |
    Matcha is a flat Design theme for GTK 3, GTK 2 and Gnome-Shell based on Arc gtk theme.
rundeps    :
    - gtk2-engine-murrine
    - gtk-engines
install    : |
    install -dm00755 $installdir/usr/share/themes
    ./Install --dest $installdir/usr/share/themes
    rm -rf $installdir/usr/share/themes/*/{cinnamon,unity,xfwm4}
