name       : matcha-gtk-theme
version    : '20200727'
release    : 10
source     :
    - https://github.com/vinceliuice/Matcha-gtk-theme/archive/2020-07-27.tar.gz : 96fb570153cc8c139ac6a428172216b0a5d382d97ccd6bb3e4e525196591af4e
homepage   : https://github.com/vinceliuice/Matcha-gtk-theme
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Matcha is a flat Design theme for GTK 3, GTK 2 and Gnome-Shell
description: |
    Matcha is a flat Design theme for GTK 3, GTK 2 and Gnome-Shell based on Arc gtk theme.
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
install    : |
    install -dm00644 $installdir/usr/share/themes
    ./install.sh --dest $installdir/usr/share/themes
    rm -rf $installdir/usr/share/themes/*/{cinnamon,unity}
