name       : matcha-gtk-theme
version    : '20191003'
release    : 3
source     :
    - https://github.com/vinceliuice/matcha/archive/2019-10-03.tar.gz : b32b3fbadcfdbee3ac6ed2c44c260da7dbf8f9ba8b9f42fa56f2e000a3a8542c
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Matcha is a flat Design theme for GTK 3, GTK 2 and Gnome-Shell
description: |
    Matcha is a flat Design theme for GTK 3, GTK 2 and Gnome-Shell based on Arc gtk theme.
rundeps    :
    - gtk2-engine-murrine
    - gtk-engines
install    : |
    install -dm00755 $installdir/usr/share/themes
    ./Install --dest $installdir/usr/share/themes
    rm -rf $installdir/usr/share/themes/*/{cinnamon,unity,xfwm4}
