name       : matcha-gtk-theme
version    : '20200618'
release    : 9
source     :
    - https://github.com/vinceliuice/Matcha-gtk-theme/archive/2020-06-18.tar.gz : 51dc637f3f5939b04f5bf7a75de051672765fbae5c5ae5f4e47ac81f72502c71
homepage   : https://github.com/vinceliuice/Matcha-gtk-theme
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Matcha is a flat Design theme for GTK 3, GTK 2 and Gnome-Shell
description: |
    Matcha is a flat Design theme for GTK 3, GTK 2 and Gnome-Shell based on Arc gtk theme.
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
install    : |
    install -dm00644 $installdir/usr/share/themes
    ./install.sh --dest $installdir/usr/share/themes
    rm -rf $installdir/usr/share/themes/*/{cinnamon,unity}
